combat_app/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from .views import CombatListView, Income, CombatApi, FieldsApi, cobmat


app_name='combat'

urlpatterns = [
    path('list/', CombatListView.as_view(), name='combat_list'),
    path('add/<pk>', Income.as_view(), name='add'),
    path('combat/<pk>', CombatApi.as_view()),
    path('combat/', CombatApi.as_view()),
    path('in_battle/<pk>', cobmat, name='combat_page'),
    path('fields/', FieldsApi.as_view())
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

game_ham/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('rest-api/', include('rest_framework.urls')),
    path('api/v1/', include('hero_app.urls')),
    path('auth/', include('main_app.urls')),
    path('user/', include('user_app.urls')),
    path('combat/', include('combat_app.urls'))
]

main_app/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from .views import RegisterView, AuthView, logout_view, HeroChooseView, HeroChooseApi

app_name = 'main_app'

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('auth/', AuthView.as_view(), name='auth'),
    path('logout/', logout_view, name='logout'),
    path('hero/', HeroChooseView.as_view(), name='hero'),
    path('hero_api/', HeroChooseApi.as_view(), name='hero_api'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

user_app/urls.py
from django.urls import path
from .views import UserPage, UserApi

app_name='user'

urlpatterns = [
    path('info/<str:username>/', UserPage.as_view(), name='user_page'),
    path('', UserApi.as_view()),
    path('<pk>/', UserApi.as_view())
]

user_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

from hero_app.models import Hero


class HeroApp(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='heroapp')
    selected_hero = models.OneToOneField(Hero, on_delete=models.CASCADE, null=True)


    @receiver(post_save, sender=User)
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            HeroApp.objects.create(user=instance)


    @receiver(post_save, sender=User)
    def save_user_profile(sender, instance, **kwargs):
        instance.heroapp.save()


# Create your models here.

user_app/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import View
from django.contrib.auth.models import User

from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework import status

from .serializers import UserShortSerializer, UserFullSerializer
from hero_app.views import CustomAPIView

class UserPage(View):
    def get(self, request, username):
        context = {
            'owner': User.objects.get(username=username)
        }
        return render(request, 'user_app/user_page.html', context)

class UserApi(CustomAPIView):
    short_serializer = UserShortSerializer
    full_serializer = UserFullSerializer
    model = User
    available_methods = ['GET', 'PUT']

user_app/templates/user_app/user_page.html
{% extends 'basic.html' %}

{% load static %}

{% block additional_head %}

<script src="{% static 'user_app/vue_scripts/user_page.js' %}"></script>
<link rel="stylesheet" href="{% static 'user_app/style.css' %}">

{% endblock %}

{% block header %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a class="nav-item nav-link active" href="{% url 'user:user_page' user.username %}">Персонажи</a>
      <a class="nav-item nav-link" href="{% url 'combat:combat_list' %}">Бои</a>
      <a class="nav-item nav-link" href="#">Настройки</a>
      <a class="nav-item nav-link" href="{% url 'main_app:logout' %}">Выход</a>
    </div>
  </div>
</nav>

{% endblock %}

{% block content %}

    <div class="main container-fluid">
        <div id="app">
            <request_handler ident='user'  id='{{user.id}}' name='{{user.username}}' is_staff='{{user.is_staff}}'></request_handler>
            <request_handler ident='owner'  id='{{owner.id}}' name='{{owner.username}}' is_staff='{{owner.is_staff}}'></request_handler>
            <heroes></heroes>
        </div>
    </div>

{% endblock %}