game_ham/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('rest-api/', include('rest_framework.urls')),
    path('api/v1/', include('hero_app.urls')),
    path('auth/', include('main_app.urls')),
    path('user/', include('user_app.urls')),
    path('combat/', include('combat_app.urls'))
]

main_app/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from .views import RegisterView, AuthView, logout_view, HeroChooseView, HeroChooseApi

app_name = 'main_app'

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('auth/', AuthView.as_view(), name='auth'),
    path('logout/', logout_view, name='logout'),
    path('hero/', HeroChooseView.as_view(), name='hero'),
    path('hero_api/', HeroChooseApi.as_view(), name='hero_api'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

main_app/models.py
from django.db import models

# Create your models here.

main_app/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.hashers import check_password

class RegisterForm(forms.ModelForm):

    password2 = forms.CharField(min_length=8, widget=forms.PasswordInput(attrs={'class':'form-control'}), required=True)
    hero_name = forms.CharField(min_length=6, max_length=24, widget=forms.TextInput(attrs={'class':'form-control'}), required=True)

    class Meta:
        model = User
        fields = ('username',  'email', 'password')

        widgets = {
            'username':forms.TextInput(attrs={'class':'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'password': forms.PasswordInput(attrs={'class': 'form-control'}),
        }

    def clean(self):
        data = super().clean()
        if data.get('password') != data.get('password2'):
            raise forms.ValidationError('Password must be exact.')
        return data

class AuthForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}),
                                required=True)
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}),
                                required=True)

    def clean(self):
        data = super().clean()
        try:
            user = User.objects.get(username=data.get('username'))
            if not check_password(data.get('password'), user.password):
                self.add_error('username', f'User {data.get("username")} doesn\'t exist or password is invalid.')
                raise forms.ValidationError('Invalid password.')
        except User.DoesNotExist:
            self.add_error('username', f'User {data.get("username")} doesn\'t exist or password is invalid.')
            raise forms.ValidationError(f'User {data.get("username")} doesn\'t exist.')
        self.user = user
        return data

main_app/views.py
from django.views.generic import View
from django.urls import reverse
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth import login, logout
from django.http import JsonResponse

from .forms import RegisterForm, AuthForm
from combat_app.combat.hero.basic import HEROES_CLASSES
from hero_app.models import Hero
import pprint


class HeroChooseApi(View):

    def get(self, request):
        output = dict(
            items=[hero.serialize() for hero in HEROES_CLASSES.values()]
        )
        return JsonResponse(data=output)


class HeroChooseView(View):

    def get(self, request):
        return render(request, 'main_app/hero_choose.html')

    def post(self, request):
        hero = request.POST.get('hero', None)
        hero_class = request.POST.get('hero_class', None)
        if not hero or not hero_class:
            return JsonResponse(data={}, status=400)
        request.session['hero'] = hero
        request.session['hero_class'] = hero_class
        request.session.save()
        return JsonResponse(data={}, status=200)


class RegisterView(View):

    def get(self, request):
        if not request.session.get('hero', None):
            return redirect(reverse('main_app:hero'))
        form = RegisterForm()
        context = {
            'form': form
        }
        return render(request, 'main_app/register.html', context)

    def post(self, request):
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = User.objects. create_user(username=form.cleaned_data['username'],
                                            password=form.cleaned_data['password'],
                                            email=form.cleaned_data['email'])
            hero = Hero.create(user=user, hero_name=form.cleaned_data['hero_name'], hero_class=request.session['hero_class'])
            user.heroapp.selected_hero = hero
            del request.session['hero']
            del request.session['hero_class']
            request.session.save()
            user.save()
            login(request, user)
            return redirect('/')
        else:
            context = {
                'form': form
            }
            return render(request, 'main_app/register.html', context)


class AuthView(View):
    def get(self, request):
        form = AuthForm()
        context = {
            'form': form
        }
        return render(request, 'main_app/auth.html', context)

    def post(self, request):
        form = AuthForm(request.POST)
        if form.is_valid():
            login(request, form.user)
            return redirect(reverse('user:user_page', args=[form.user.username]))
        else:
            context = {
                'form': form
            }
            return render(request, 'main_app/auth.html', context)


def logout_view(request):
    if request.method == 'GET':
        logout(request)
        return redirect(reverse('main_app:auth'))

main_app/templates/main_app/auth.html
{% extends 'basic_register.html' %}

{% block title %}Register page.{% endblock %}

{% block content %}

<form action="{% url 'main_app:auth' %}" method="POST">
    {% csrf_token %}
    <div class="d-flex flex-column">
        {% for item in form %}
            <div class="form-group">
                <div class="w-50 d-inline">
                    {{item.label}}
                </div>
                <div class="w-50 d-inline">
                    {{item}}
                </div>
                <div class="w-50 d-inline">
                    {{item.errors}}
                </div>
            </div>
        {% endfor %}
        <input type="submit" class="btn btn-primary" value="Отправить">
        <a href="{% url 'main_app:hero' %}" class='d-block'>Регистрация</a>
    </div>
</form>

{% endblock %}

main_app/templates/main_app/hero_choose.html
{% extends 'basic.html' %}

{% load static %}

{% block additional_head %}

<script src="{% static 'main_app/vue_scripts/choose_hero.js' %}"></script>
<link rel="stylesheet" href="{% static 'main_app/style.css' %}">

{% endblock %}

{% block content %}
	<div class="row">
	    <div id="app" class='w-100'>
	    	<heroes></heroes>
	    </div>
    </div>

{% endblock %}

main_app/templates/main_app/register.html
{% extends 'basic_register.html' %}

{% block title %}Register page.{% endblock %}

{% block content %}

{{request.session.hero}}

<form action="{% url 'main_app:register' %}" method="POST">
    {% csrf_token %}
    <div class="d-flex flex-column">
        {% for item in form %}
            <div class="form-group">
                <div class="w-50 d-inline">
                    {{item.label}}
                </div>
                <div class="w-50 d-inline">
                    {{item}}
                </div>
                <div class="w-50 d-inline">
                    {{item.errors}}
                </div>
            </div>
        {% endfor %}
        <input type="submit" class="btn btn-primary" value="Отправить">
    </div>
</form>

{% endblock %}